### ISSUE TITLE
Skid

### ISSUE THREAD

**Issue by ercenterprises** [xtekky/xtekky#1]
`staticmethod` cannot have the `self` parameter 🤡

**Comment by xtekky** [comment]
I dont give a fck, this is not supposed to be a working python script, get a life instead of critisizing ppl's readmes 🤡

**Comment by ghost** [comment]
> I dont give a fck, this is not supposed to be a working python script, get a life instead of critisizing ppl's readmes 🤡

The issue is you **cannot code**. This is a rookie mistake 🤣

**Comment by phishontop** [comment]
> `staticmethod` cannot have the `self` parameter 🤡

woah, you know basic python OOP!!!!

**Comment by ghost** [comment]
> > `staticmethod` cannot have the `self` parameter 🤡
> 
> woah, you know basic python OOP!!!!

- xtekky doesn't though
- i'm going to assume you're a skid because of your username 
- and that terrible PEP8 code 😂

**Comment by phishontop** [comment]
> > > `staticmethod` cannot have the `self` parameter 🤡
> > 
> > 
> > woah, you know basic python OOP!!!!
> 
>     * xtekky doesn't though
> 
>     * i'm going to assume you're a skid because of your username
> 
>     * and that terrible PEP8 code 😂

saying my code doesn't follow pep8 is just ironic at this point, feel free to add my on discord
we can talk more so u can see im not a skid, I have currently been doing python for 3 years and a couple months

Discord: phish#7936

**Comment by xtekky** [comment]
can yall get a life or something lmfao just make a pull if it's so extreme that I put self with staticmethod in my readme pseudo code, instead of critisizing, + it would theoretically even work, point
